-- ============================================================
-- DataFinsight Email Tracker — Combined Migration
-- Run this once in the Supabase SQL Editor
-- Safe to re-run (uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS)
-- ============================================================

-- ============================================================
-- 1. EXTEND JOBS TABLE
--    Add business-context columns needed by the Compose UI.
--    Existing 40 rows and all FK references are preserved.
-- ============================================================

ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS description    text,
  ADD COLUMN IF NOT EXISTS company_name   text,
  ADD COLUMN IF NOT EXISTS location       text,
  ADD COLUMN IF NOT EXISTS contact_email  text,
  ADD COLUMN IF NOT EXISTS status         text DEFAULT 'active'
    CHECK (status IN ('active', 'paused', 'closed'));

-- ============================================================
-- 2. CREATE email_opens
--    Repo A tracking pixel writes here (table was missing).
-- ============================================================

CREATE TABLE IF NOT EXISTS email_opens (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id  uuid        UNIQUE REFERENCES conversations(id) ON DELETE CASCADE,
  candidate_id     uuid        REFERENCES candidates(id) ON DELETE SET NULL,
  email            text,
  opened_at        timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_opens_conversation_id
  ON email_opens (conversation_id);

CREATE INDEX IF NOT EXISTS idx_email_opens_candidate_id
  ON email_opens (candidate_id);

-- ============================================================
-- 3. CREATE email_drafts
--    Stores pre-send emails generated by the Compose tab.
-- ============================================================

CREATE TABLE IF NOT EXISTS email_drafts (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id           uuid        REFERENCES jobs(id) ON DELETE CASCADE,
  candidate_email  text        NOT NULL,
  subject          text,
  body             text,
  conversation_id  uuid        REFERENCES conversations(id) ON DELETE SET NULL,
  status           text        NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'sent', 'discarded')),
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_drafts_job_id
  ON email_drafts (job_id);

CREATE INDEX IF NOT EXISTS idx_email_drafts_status
  ON email_drafts (status);

-- Auto-update updated_at on email_drafts
CREATE OR REPLACE FUNCTION update_email_drafts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_email_drafts_updated_at ON email_drafts;
CREATE TRIGGER trg_email_drafts_updated_at
  BEFORE UPDATE ON email_drafts
  FOR EACH ROW EXECUTE FUNCTION update_email_drafts_updated_at();

-- ============================================================
-- 4. CREATE audit_log
--    Append-only log of all send events for traceability.
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_log (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type   text        NOT NULL,   -- 'email_sent', 'draft_created', 'draft_discarded'
  entity_type  text,                   -- 'conversation', 'job', 'candidate'
  entity_id    text,
  payload      jsonb,
  created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_event_type
  ON audit_log (event_type);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
  ON audit_log (created_at DESC);

-- ============================================================
-- 5. ENABLE ROW-LEVEL SECURITY
--    Removes the Supabase "table accessible by anyone" warning.
--    Grants the anon role full access so existing Azure Function
--    integrations (Repos A & B) continue to work unchanged.
-- ============================================================

DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'jobs','candidates','conversations','conversation_emails',
    'attachments','email_unsubscribes','candidate_profiles',
    'conversation_status','email_opens','email_drafts','audit_log'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    -- Drop and recreate so re-runs are safe
    EXECUTE format('DROP POLICY IF EXISTS anon_all ON %I', t);
    EXECUTE format(
      'CREATE POLICY anon_all ON %I FOR ALL TO anon USING (true) WITH CHECK (true)',
      t
    );
  END LOOP;
END $$;

-- ============================================================
-- VERIFICATION
-- Uncomment to verify after running:
-- ============================================================

-- SELECT table_name, row_security
-- FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name IN (
--   'jobs','candidates','conversations','conversation_emails',
--   'attachments','email_unsubscribes','candidate_profiles',
--   'conversation_status','email_opens','email_drafts','audit_log'
-- )
-- ORDER BY table_name;

-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'jobs' ORDER BY ordinal_position;
